import NavBar from "@/components/NavBar/navBar"
import "./layout.scss"
import {  Poppins  } from 'next/font/google'
 
const roboto = Poppins({
  weight: ['100','400','500','600','700'],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="body-layout">
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
