import NavBar from "@/components/NavBar/navBar"
import "./layout.scss"
import {  Lilita_One, Roboto  } from 'next/font/google'
 
// If loading a variable font, you don't need to specify the font weight
const lilitaOne = Lilita_One({
  weight: '400',
})

const roboto = Roboto({
  weight: ['100','400','700'],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="body-layout">
        <NavBar/>
        {children}
      </body>
    </html>
  );
}
